version: "3.7"
services:
  nginx:
    image: "spring-boot/nginx:v1"
    healthcheck:
      test: ["CMD", "cat", "/var/run/nginx.pid"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - web-ui1
      - web-ui2
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - webnet
  web-ui1:
    image: "spring-boot/web-ui:v1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./logs/web-ui1:/App/springbootsampleapp/logs
    ports:
      - "4001:8080"
    networks:
      - webnet
  web-ui2:
    image: "spring-boot/web-ui:v1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./logs/web-ui2:/App/springbootsampleapp/logs
    ports:
      - "4002:8080"
    networks:
      - webnet
networks:
  webnet: